before_install:
  - wget -q http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xf rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - sudo ./rust-nightly-x86_64-unknown-linux-gnu/install.sh
install:
  - cd ..
  - time wget -q http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - time wget -q http://hivelocity.dl.sourceforge.net/project/sdl2gfx/SDL2_gfx-1.0.0.tar.gz
  - time wget -q http://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz
  - time tar xf SDL2-*.tar.gz
  - time tar xf SDL2_gfx-*.tar.gz
  - time tar xf SDL2_ttf-*.tar.gz
  - cd SDL2-*
  - ./configure && make && sudo make install
  - cd -
  - cd SDL2_gfx-*
  - ./configure && make && sudo make install
  - cd -
  - cd SDL2_ttf-*
  - ./configure && make && sudo make install
  - cd -
  - git clone https://github.com/andelf/rust-sdl2.git
  - git clone https://github.com/andelf/rust-sdl2_gfx.git
  - git clone https://github.com/andelf/rust-sdl2_ttf.git
  - (cd rust-sdl2 && make)
  - rustc rust-sdl2/src/sdl2/lib.rs
  - rustc -L. rust-sdl2_gfx/src/sdl2_gfx/lib.rs
  - rustc -L. rust-sdl2_ttf/src/sdl2_ttf/lib.rs
script:
  - rustc -L. rust-2048/src/main.rs
