[package]

name = "game2048"
description = "2048 game in Rust"
repository = "https://github.com/andelf/rust-2048"
version = "0.0.1"
license = "MIT"
authors = [ "ShuYu Wang <andelf@gmail.com>" ]
keywords = [ "game", "2048" ]

[[bin]]

name = "game2048"
path = "src/main.rs"

[dependencies]

sdl2 = "~0.0.3"

sdl2_ttf = "~0.0.3"

sdl2_gfx = "~0.0.3"
